# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk9 
  - oraclejdk11

#Cache downloaded Maven artifacts between builds
cache:
  directories:
      - "${HOME}/.m2"
  
notifications:
  email: false
  slack: wlc:Kinf3gdySndcFTBtjcci3rJN
